#!/bin/bash

set -e

# Do not user SCRIPT_DIR as it would be overwritten by platform.sh
SCR_DIR=$(dirname $0)

. $SCR_DIR/bin/platform.sh

# Download firefox if not already done
if [ ! -f $FIREFOX_BIN ]; then
  $SCR_DIR/bin/fetch-firefox.sh
fi

if [ ! -d $SCR_DIR/profile ]; then
  $SCR_DIR/bin/create-dev-profile.sh $SCR_DIR/profile
fi

$FIREFOX_BIN -profile $SCR_DIR/profile --no-remote $@
